### ISSUE TITLE
Add PWA Support.

### ISSUE THREAD

**Issue by vivek-30** [vivek-30/Chat-App#2]
Benifits of PWA -
1. App Like Look and Feel.
2. Better Performance.
3. Good offline experience.
4. Push Notification Functionality.
5. Fast Installation.
6. Enhanced Security.
7. And many more things it offers .

**Comment by vivek-30** [comment]
#### Sub-Tasks -
- [ ] Create manifest.json file.
- [ ] Create a service worker file.
- [ ] Test it and marked it completed
- [ ] Done. Close this issue. 🥳
